// --- DICCIONARIO DE SKUS ---
const CATALOGO_SKUS = {
    "HP - Prodesk 600G5": "2C430LS",
    "HP PRO 400 SFF G9": "2VG42AV",
    "HP - Prodesk 600G6": "37L03LS",
    "HP LaserJet Managed E40040dn": "3PZ35A",
    "HP - Elitebook 1040 G5": "5SH97LT",
    "LG - 20M37A": "5SH97LT",
    "HP Elitebook 840 G5": "6CE32LA",
    "HP - Prodesk 400G9 - backup": "7D7L9LS",
    "HP - Laser 408dn": "7UQ75A",
    "Hp - 408dn s/anexo3": "7UQ75A",
    "HP - Prodesk 600G4": "7XA20LS",
    "Hp - Prodesk 600g4 s/anexo3": "7XA20LS",
    "HP PB440 G10": "7Z7H2LT",
    "HP - Digital Sender Flow 8500 fn2": "L2762A",
    "LG - 29UM68-P": "6916L",
    "SAMSUNG - ML 4020": "SS383Q",
    "Samsung - Ml 4020 s/anexo3": "SS383Q",
    "HP EliteBook 840 G8": "26D62AV",
    "USB-C G5 Essential Dock": "72C71AA",
    "Hp - Thunderlbolt Dock G2 s/anexo3": "72C71AA",
    "HP - V214A": "3WP69AA",
    "LG - 29UM68": "6916L",
    "HP - Thunderbolt Dock 120W G2": "72C71AA",
    "Monitor FHD HP P22 G4 22": "64X86AA",
    "HP EliteBook 1040 G8": "1H9X2AV",
    "Hp - Ultraslim D9y32aa s/anexo3": "D9Y32Aa",
    "Hp - Enterprise Flow 8500 s/anexo3": "L2762A",
    "HP - UltraSlim": "D9Y32Aa",
    "Hp - Prodesk 600g6 s/anexo3": "9BD70AV",
    "Hp - Elitebook 840 G5 s/anexo3": "3RF31LT",
    "HP USD-DOCK G5": "5TW10AA",
    "Monitor HP P22 G5 FHDHP": "64X86AA",
    "Samsung - MultiXpress SL-M5360R": "SS383Q",
    "ScanJet Flow N6600 fnw1": "20G08A"
};

// --- DICCIONARIO DE CIUDADES ---
const CATALOGO_CIUDADES = {
    // --- COYHAIQUE ---
    "1° Juzgado De Letras De Coyhaique": "COYHAIQUE",
    "Juzgado De Familia De Coyhaique": "COYHAIQUE",
    "Juzgado de Letras y Garantia De Aisen": "AISEN",
    "Juzgado De Letras y Garantia De Chile Chico": "CHILE CHICO",
    "Juzgado De Letras Y Garantia De Cisnes": "CISNES",
    "Juzgado De Garantia De Coyhaique": "COYHAIQUE",
    "Tribunal De Juicio Oral En Lo Penal De Coyhaique": "COYHAIQUE",
    "Juzgado De Letras Del Trabajo De Coyhaique": "COYHAIQUE",
    "Corte De Apelaciones De Coyhaique": "COYHAIQUE",
    "Corporacion Administrativa De Coyhaique": "COYHAIQUE",
    "Juzgado De Letras Y Garantia De Cochrane": "COCHRANE",
    "Oficina De Personal De Coihaique": "COYHAIQUE",
    // --- ANTOFAGASTA ---
    "1° Juzgado Civil De Antofagasta": "ANTOFAGASTA",
    "2° Juzgado Civil De Antofagasta": "ANTOFAGASTA",
    "3° Juzgado Civil De Antofagasta": "ANTOFAGASTA",
    "4° Juzgado Civil De Antofagasta": "ANTOFAGASTA",
    "Juzgado De Familia De Antofagasta": "ANTOFAGASTA",
    "Juzgado De Letras Del Trabajo De Antofagasta": "ANTOFAGASTA",
    "Juzgado De Letras De Tocopilla": "TOCOPILLA",
    "Juzgado Del Trabajo De Antofagasta": "ANTOFAGASTA",
    "Tribunal De Juicio Oral En Lo Penal De Calama": "CALAMA",
    "Juzgado De Garantia De Calama": "CALAMA",
    "Corporacion Administrativa De Antofagasta": "ANTOFAGASTA",
    "Tribunal De Juicio Oral En Lo Penal De Antofagasta": "ANTOFAGASTA",
    "Juzgado De Garantia De Tocopilla": "TOCOPILLA",
    "Juzgado De letras Y Garantia De Maria Elena": "MARIA ELENA",
    "Juzgado De Letras Y Garantia De Taltal": "TALTAL",
    "Juzgado de Letras De Mejillones": "MEJILLONES",
    "1° Juzgado De Letras De Calama": "CALAMA",
    "Corte De Apelaciones de Antofagasta": "ANTOFAGASTA",
    "2° Juzgado De Letras De Calama": "CALAMA",
    "3° Juzgado De Letras De Calama": "CALAMA",
    "Juzgado De Letras Del Trabajo De Calama": "CALAMA",
    "Juzgado De Familia De Calama": "CALAMA",
    "Juzgado De Garantia De Antofagasta": "ANTOFAGASTA",
    "Corporacion Administrativa De Antofagasta - Bodega Zonal De Antofagasta": "ANTOFAGASTA",
    "UNIDAD APOYO TECNICO ADMINISTRATIVO DE ANTOFAGASTA": "ANTOFAGASTA",
    // --- ARICA ---
    "1° Juzgado De Letras De Arica": "ARICA",
    "2° Juzgado De Letras De Arica": "ARICA",
    "3° Juzgado De Letras De Arica": "ARICA",
    "Juzgado De Familia De Arica": "ARICA",
    "Corte De Apelaciones De Arica": "ARICA",
    "Juzgado De Garantia De Arica": "ARICA",
    "Tribunal De Juicio Oral En Lo Penal De Arica": "ARICA",
    "Corporacion Administrativa De Arica": "ARICA",
    "Juzgado De Letras De Arica": "ARICA",
    "Juzgado De Letras Del Trabajo De Arica": "ARICA",
    "Centro De Observ. Y Control De Cump. De Medidas De Protec. De Familia Arica": "ARICA",
    // --- COPIAPO ---
    "1° Juzgado De Letras De Copiapo": "COPIAPO",
    "2° Juzgado De Letras De Copiapo": "COPIAPO",
    "3° Juzgado De Letras De Copiapo": "COPIAPO",
    "4° Juzgado De Letras De Copiapo": "COPIAPO",
    "Corte De Apelaciones De Copiapo": "COPIAPO",
    "1° Juzgado De Letras De Vallenar": "VALLENAR",
    "2° Juzgado De Letras De Vallenar": "VALLENAR",
    "Juzgado De Garantia De Copiapo": "COPIAPO",
    "Juzgado De Letras De Diego De Almagro": "DIEGO DE ALMAGRO",
    "Juzgado De Letras Y Garantia De Caldera": "CALDERA",
    "Juzgado De Letras Y Garantia De Freirina": "FREIRINA",
    "Corporacion Administrativa De Copiapo": "COPIAPO",
    "Corte De Apelacioes De Copiapo": "COPIAPO",
    "Tribunal De Juicio Oral En Lo Penal De Copiapo": "COPIAPO",
    "Juzgado De familia De Copiapo": "COPIAPO",
    "Juzgado De Familia De Vallenar": "VALLENAR",
    "Juzgado De Letras Y Garantia De ChaÑaral": "CHAÑARAL",
    "Juzgado De Garantia De Diego De Almagro": "DIEGO DE ALMAGRO",
    "Juzgado De Garantia De Vallenar": "VALLENAR",
    "Corporacion Administrativa Central": "SANTIAGO",
    "Juzgado De Letras Del Trabajo De Copiapo": "COPIAPO",
    // --- CONCEPCION ---
    "1° Juzgado Civil De Concepcion": "CONCEPCION",
    "1° Juzgado Civil De Talcahuano": "TALCAHUANO",
    "2° Juzgado Civil De Concepcion": "CONCEPCION",
    "2° Juzgado Civil De Talcahuano": "TALCAHUANO",
    "3° Juzgado Civil De Concepcion": "CONCEPCION",
    "Juzgado De Familia De Concepcion": "CONCEPCION",
    "Juzgado De Familia De Coronel": "CORONEL",
    "Juzgado De Familia De Los Angeles": "LOS ANGELES",
    "Juzgado De Familia De Talcahuano": "TALCAHUANO",
    "Juzgado De Familia De Tome": "TOME",
    "Juzgado De Familia De Yumbel": "YUMBEL",
    "Juzgado De Letras Del Trabajo De Concepcion": "CONCEPCION",
    "Tribunal De Juicio Oral En Lo Penal De Cañete": "CAÑETE",
    "1° Juzgado De Letras De Los Angeles": "LOS ANGELES",
    "1° Juzgado De Letras De Coronel": "CORONEL",
    "2° Juzgado De Letras De Los Angeles": "LOS ANGELES",
    "Juzgado De Garantia De Arauco": "ARAUCO",
    "Juzgado De Garantia De Chiguayante": "CHIGUAYANTE",
    "Juzgado De Garantia De Coronel": "CORONEL",
    "Juzgado De Garantia De Los Angeles": "LOS ANGELES",
    "Juzgado De Garantia De San Pedro De La Paz": "SAN PEDRO DE LA PAZ",
    "Juzgado De Garantia De Talcahuano": "TALCAHUANO",
    "Juzgado De Garantia De Tome": "TOME",
    "Juzgado De Letras De CaÑete": "CAÑETE",
    "Juzgado De Letras Y Garantia De Cabrero": "CABRERO",
    "Tribunal De Juicio Oral En Lo Penal De Concepcion": "CONCEPCION",
    "Corporacion Administrativa De Concepcion": "CONCEPCION",
    "Juzgado De Cobranza Laboral Y Previsional De Concepcion": "CONCEPCION",
    "Corte De Apelaciones De Concepcion": "CONCEPCION",
    "Juzgado De Letras Y Garantia De Santa Barbara": "SANTA BARBARA",
    "Juzgado De Letras Y Garantia De Curanilahue": "CURANILAHUE",
    "Juzgado De Garantia De Concepcion": "CONCEPCION",
    "Juzgado De Letras Y Garantia De Nacimiento": "NACIMIENTO",
    "Juzgado De Letras Y Garantia De Laja": "LAJA",
    "2° Juzgado De Letras De Coronel": "CORONEL",
    "Juzgado De Letras De Arauco": "ARAUCO",
    "Juzgado De Letras Y Garantia De Lota": "LOTA",
    "Juzgado De Letras Y Garantia De Florida": "FLORIDA",
    "Juzgado De Letras Y Garantia De Lebu": "LEBU",
    "Juzgado De Letras Y Garantia De Mulchen": "MULCHEN",
    "Juzgado De Letras Y Garantia De Santa Juana": "SANTA JUANA",
    "Juzgado De Letras Y Garantia De Yumbel": "YUMBEL",
    "Tribunal De Juicio Oral En Lo Penal De Los Angeles": "SANTA BARBARA",
    "Juzgado De Letras De Tome": "TOME",
    "Juzgado De Letras Del Trabajo De Los Angeles": "CONCEPCION",
    "Juzgado De Cobranza Laboral Y Previsional De Conce": "CONCEPCION",
    "Juzgado De Garantia De CaÑete": "CAÑETE",
    "Centro De Notificaciones De Concepción": "CONCEPCION",
    "Centro De Notificaciones De Los Angeles": "LOS ANGELES",
    // --- LA SERENA ---
    "1° Juzgado De Letras De Coquimbo": "COQUIMBO",
    "1° Juzgado De Letras De La Serena": "LA SERENA",
    "2° Juzgado De Letras De Coquimbo": "COQUIMBO",
    "Juzgado De Letras Del Trabajo De La Serena": "LA SERENA",
    "Juzgado De Letras Y Garantia De Combarbala": "COMBARBALA",
    "2°Juzgado De Letras De La Serena": "LA SERENA",
    "Corporacion Administrativa De La Serena": "LA SERENA",
    "3° Juzgado De Letras De La Serena": "LA SERENA",
    "3° Juzgado De Letras De Ovalle": "OVALLE",
    "Corte De Apelaciones De La Serena": "LA SERENA",
    "1° Juzgado De Letras De Ovalle": "OVALLE",
    "2° Juzgado De Letras De Ovalle": "OVALLE",
    "Juzgado De Familia De Coquimbo": "COQUIMBO",
    "Juzgado De Letras De Vicuña": "VICUÑA",
    "Tribunal De Juicio Oral En Lo Penal De Ovalle": "OVALLE",
    "Juzgado De Letras Y Garantia De Los Vilos": "LOS VILOS",
    "Juzgado De Letras Y Garantia De Andacollo": "ANDACOLLO",
    "Unidad De Apoyo A Los Juzgados Civiles De La Serena": "LA SERENA",
    "Juzgado De Letras De Illapel": "ILLAPEL",
    "Juzgado De Garantia De La Serena": "LA SERENA",
    "Juzgado De Garantia de Coquimbo": "COQUIMBO",
    "Juzgado De Familia De La Serena": "LA SERENA",
    "Juzgado De Familia De Ovalle": "OVALLE",
    "Juzgado De Garantia De Los Vilos": "LOS VILOS",
    "3° Juzgado De Letras De Coquimbo": "COQUIMBO",
    "Juzgado De Garantia De Ovalle": "OVALLE",
    "Juzgado De Garantia De Illapel": "ILLAPEL",
    "Juzgado De Garantia De VicuÑa": "VICUÑA",
    "Tribunal De Juicio Oral En Lo Penal De La Serena": "LA SERENA",
    "Centro De Observ. Y Control De Cump. De Medidas De Protec. De Familia La Serena": "LA SERENA",
    "Unidad Apoyo Tecnico Administrativo De La Serena": "LA SERENA",
    // --- TEMUCO ---
    "1° Juzgado Civil De Temuco": "TEMUCO",
    "2° Juzgado Civil De Temuco": "TEMUCO",
    "3° Juzgado Civil De Temuco": "TEMUCO",
    "1°Jugado Civil De Temuco": "TEMUCO",
    "2°Juzgado Civil De Temuco": "TEMUCO",
    "Juzgado De Familia De Angol": "ANGOL",
    "Corte De Apelaciones De Temuco": "TEMUCO",
    "Juzgado De Garantia De Lautaro": "LAUTARO",
    "Juzgado De Garantia De Loncoche": "LONCOCHE",
    "Juzgado De Garantia De Nueva Imperial": "NUEVA IMPERIAL",
    "Juzgado De Garantia De Pitrufquen": "PITRUFQUEN",
    "Juzgado De Garantia De Temuco": "TEMUCO",
    "Juzgado De Garantia De Victoria": "VICTORIA",
    "Juzgado De Garantia De Villarrica": "VILLARRICA",
    "Juzgado De Letras Del Trabajo De Temuco": "TEMUCO",
    "Tribunal De Juicio Oral En Lo Penal De Angol": "ANGOL",
    "Tribunal De Juicio Oral En Lo Penal De Temuco": "TEMUCO",
    "Tribunal De Juicio Oral En Lo Penal De Villarrica": "VILLARRICA",
    "Corporacion Administrativa De Temuco": "TEMUCO",
    "Juzgado De Letras De Pitrufquen": "PITRUFQUEN",
    "Juzgado De Letras y Garantia De Traiguen": "TRAIGUEN",
    "Juzgado De Letras De Lautaro": "LAUTARO",
    "1° Juzgado De Letras De Angol": "ANGOL",
    "Juzgado De Familia De Temuco": "TEMUCO",
    "Juzgado De Garantia De Angol": "ANGOL",
    "Juzgado De Letras De Loncoche": "LONCOCHE",
    "Juzgado De Letras De Nueva Imperial": "NUEVA IMPERIAL",
    "Juzgado De Letras Y Garantia De Carahue": "CARAHUE",
    "Juzgado De Letras Y Garantia De Collipulli": "COLLIPULLI",
    "Juzgado De Letras Y Garantia De Curacautin": "CURACAUTIN",
    "Juzgado De Letras Y Garantia De Pucon": "PUCON",
    "Juzgado De Letras Y Garantia De Puren": "PUREN",
    "Juzgado De Letras Y Garantia De Tolten": "TOLTEN",
    "Juzgado De Letras De Villarrica": "VILLARRICA",
    "Juzgado De Letras De Victoria": "VICTORIA",
    "Unidad De Derechos Humanos De Temuco": "TEMUCO",
    "Corporacion Administrativa De Temuco - Centro De Notificaciones De Temuco": "TEMUCO",
    "Corporacion Administrativa De Temuco - Unidad De Apoyo A Los Juzgados Civiles De Temuco": "TEMUCO",
    // --- RANCAGUA ---
    "Juzgado De Familia De Rengo": "RENGO",
    "Juzgado De Familia De San Fernando": "SAN FERNANDO",
    "Juzgado De Familia De Santa Cruz": "SANTA CRUZ",
    "Juzgado De Letras Del Trabajo De Rancagua": "RANCAGUA",
    "Tribunal De Juicio Oral En Lo Penal De Rancagua": "RANCAGUA",
    "Tribunal De Juicio Oral En Lo Penal De Santa Cruz": "SANTA CRUZ",
    "Juzgado De Familia De Rancagua": "RANCAGUA",
    "1° Juzgado Civil De Rancagua": "RANCAGUA",
    "Juzgado De Garantia De Rancagua": "RANCAGUA",
    "1° Juzgado De Letras De San Fernando": "SAN FERNANDO",
    "1° Juzgado De Letras De Santa Cruz": "SANTA CRUZ",
    "2° Juzgado Civil De Rancagua": "RANCAGUA",
    "Corte De Apelaciones De Rancagua": "RANCAGUA",
    "Juzgado De Garantia De Rengo": "RENGO",
    "Juzgado De Garantia De San Fernando": "SAN FERNANDO",
    "1° Juzgado De Letras De Rengo": "RENGO",
    "Juzgado De Letras y Garantia De Pichilemu": "PICHILEMU",
    "2° Juzgado De Letras De San Fernando": "SAN FERNANDO",
    "Juzgado De Letras De San Vicente": "SAN VICENTE",
    "Juzgado De Letras y Garantia De Litueche": "LITUECHE",
    "Juzgado De Letras Y Garantia De Peumo": "PEUMO",
    "Juzgado De Letras y Garantia de Peralillo": "PERALILLO",
    "Juzgado De Garantia de Graneros": "GRANEROS",
    "Corporacion Administrativa De Rancagua": "RANCAGUA",
    "Juzgado De Garantia Y Rancagua": "RANCAGUA",
    "Juzgado De Garantia De San Vicente": "SAN VICENTE",
    "Juzgado De Garantia De Santa Cruz": "SANTA CRUZ",
    "Tribunal Juicio Oral En Lo Penal De San Fernando": "SAN FERNANDO",
    "Corporacion Administrativa De Rancagua - Bodega Zonal De Rancagua": "RANCAGUA",
    "Juzgado del Trabajo de Rancagua": "RANCAGUA",
    // --- PUERTO MONTT ---
    "Juzgado De Familia De Ancud": "ANCUD",
    "Juzgado De Familia De Castro": "CASTRO",
    "Juzgado De Familia De Puerto Varas": "PUERTO VARAS",
    "Tribunal De Juicio Oral En Lo Penal De Castro": "CASTRO",
    "Tribunal Juicio Oral En Lo Penal De Puerto Montt": "PUERTO MONTT",
    "2° Juzgado Civil De Puerto Montt": "PUERTO MONTT",
    "1° Juzgado Civil De Puerto Montt": "PUERTO MONTT",
    "1° Juzgado De Letras De Osorno": "OSORNO",
    "2° Juzgado De Letras De Osorno": "OSORNO",
    "1° Juzgado De Letras De Puerto Varas": "PUERTO VARAS",
    "Juzgado De Familia De Osorno": "OSORNO",
    "Juzgado De Familia De Puerto Montt": "PUERTO MONTT",
    "Juzgado De Letras De Rio Negro": "RIO NEGRO",
    "Juzgado De Letras Del Trabajo De Osorno": "OSORNO",
    "Juzgado De Letras Del Trabajo De Puerto Montt": "PUERTO MONTT",
    "Juzgado De Letras De Ancud": "ANCUD",
    "Corte De Apelaciones De Puerto Montt": "PUERTO MONTT",
    "Corporacion Administrativa De Puerto Montt": "PUERTO MONTT",
    "Juzgado De Garantia De Ancud": "ANCUD",
    "Juzgado De Letras Y Garantia De Quellon": "QUELLON",
    "Juzgado De Letras Y Garantia De Hualaihue": "HUALAIHUE",
    "Tribunal De Juicio Oral En Lo Penal De Osorno": "OSORNO",
    "Juzgado De Letras De Castro": "CASTRO",
    "Juzgado De Letras Y Garantia De Calbuco": "CALBUCO",
    "Juzgado De Letras Y Garantia De Los Muermos": "LOS MUERMOS",
    "Juzgado De Letras Y Garantia De Maullin": "MAULLIN",
    "Juzgado De Letras Y Garantia De Quinchao": "QUINCHAO",
    "Juzgado De Garantia De Puerto Montt": "PUERTO MONTT",
    "Juzgado De Letras Del Trabajo De Castro": "CASTRO",
    "Juzgado De Letras Y Garantia De Chaiten": "CHAITEN",
    "Juzgado De Garantia De Castro": "CASTRO",
    "Juzgado De Garantia De Osorno": "OSORNO",
    "Juzgado De Garantia De Rio Negro": "RIO NEGRO",
    "Juzgado De Garantia De Puerto Varas": "PUERTO VARAS",
    "Corporacion Administrativa De Puerto Montt - Centro Notificaciones Judiciales": "PUERTO MONTT",
    "Corporacion Administrativa De Puerto Montt - Unidad Centralizada De Cumplimiento De Familia": "PUERTO MONTT",
    "Centro De Notificaciones De Puerto Montt": "PUERTO MONTT",
    // --- VALDIVIA ---
    "1° Juzgado Civil De Valdivia": "VALDIVIA",
    "Corte De Apelaciones De Valdivia": "VALDIVIA",
    "Juzgado De Letras Y Garantia De Panguipulli": "PANGUIPULLI",
    "Corporacion Administrativa De Valdivia": "VALDIVIA",
    "Juzgado De Garantia De Valdivia": "VALDIVIA",
    "Tribunal De Juicio Oral En Lo Penal De Valdivia": "VALDIVIA",
    "Juzgado De Letras Y Garantia De Paillaco": "PAILLACO",
    "Juzgado De Letras De Los Lagos": "LOS LAGOS",
    "Juzgado De Familia De Valdivia": "VALDIVIA",
    "2° Juzgado Civil De Valdivia": "VALDIVIA",
    "Juzgado De Letras Del Trabajo De Valdivia": "VALDIVIA",
    "Juzgado De Letras De Mariquina": "MARIQUINA",
    "Juzgado De Letras Y Garantia De La Union": "LA UNION",
    "Juzgado De Letras Y Garantia De Rio Bueno": "RIO BUENO",
    "Juzgado De Garantia De Los Lagos": "LOS LAGOS",
    "Juzgado De Garantia De Mariquina": "MARIQUINA",
    "UNIDAD APOYO TECNICO ADMINISTRATIVO DE PUERTO MONT": "LOS LAGOS",
    "CORTE SUPREMA DE JUSTICIA PUERTO MONTT": "LOS LAGOS",
    // --- PUNTA ARENAS ---
    "1° Juzgado De Letras De Punta Arenas": "PUNTA ARENAS",
    "2° Juzgado De Letras De Punta Arenas": "PUNTA ARENAS",
    "3° Juzgado De Letras De Punta Arenas": "PUNTA ARENAS",
    "Juzgado De Familia De Punta Arenas": "PUNTA ARENAS",
    "Tribunal Juicio Oral En Lo Penal De Punta Arenas": "PUNTA ARENAS",
    "Juzgado De Letras Y Garantia De Natales": "NATALES",
    "Juzgado De Letras Y Garantia De Porvenir": "PORVENIR",
    "Juzgado De Letras De Cabo De Hornos": "CABO DE HORNOS",
    "Corporacion Administrativa De Punta Arenas": "PUNTA ARENAS",
    "Corte De Apelaciones De Punta Arenas": "PUNTA ARENAS",
    "Juzgado De Garantia De Punta Arenas": "PUNTA ARENAS",
    "Juzgado De Letras Del Trabajo De Punta Arenas": "PUNTA ARENAS",
    // --- TALCA ---
    "Juzgado De Familia De Constitucion": "CONSTITUCION",
    "1° Juzgado De Letras De Curico": "CURICO",
    "Juzgado De Familia De Parral": "PARRAL",
    "Juzgado De Garantia De Talca": "TALCA",
    "Juzgado De Letras Del Trabajo De Curico": "CURICO",
    "Corporacion Administrativa De Talca": "TALCA",
    "Juzgado De Letras De Cauquenes": "CAUQUENES",
    "Juzgado De Letras Del Trabajo De Talca": "TALCA",
    "Juzgado De Garantia De San Javier": "SAN JAVIER",
    "Juzgado De Garantia De Molina": "MOLINA",
    "Tribunal De Juicio Oral En Lo Penal De Talca": "TALCA",
    "Tribunal De Juicio Oral En Lo Penal De Curico": "CURICO",
    "Tribunal De Juicio Oral En Lo Penal De Cauquenes": "CAUQUENES",
    "Tribunal De Juicio Oral En Lo Penal De Linares": "LINARES",
    "Juzgado De Garantia De Constitucion": "CONSTITUCION",
    "Juzgado De Garantia De Parral": "PARRAL",
    "Juzgado De Letras Y Garantia De Chanco": "CHANCO",
    "Juzgado De Letras Y Garantia De Curepto": "CUREPTO",
    "Juzgado De Letras Y Garantia De Licanten": "LICANTEN",
    "Juzgado De Garantia De Curico": "CURICO",
    "Corte De Apelaciones De Talca": "TALCA",
    "Juzgado De Letras De Parral": "PARRAL",
    "Juzgado De Letras De Molina": "MOLINA",
    "Juzgado De Familia De Curico": "CURICO",
    "Juzgado De Garantia De Cauquenes": "CAUQUENES",
    "Juzgado De Familia De Talca": "TALCA",
    "Juzgado De Garantia De Linares": "LINARES",
    "Juzgado De Familia De Linares": "LINARES",
    "4° Juzgado De Letras De Talca": "TALCA",
    "3° Juzgado De Letras De Talca": "TALCA",
    "2° Juzgado De Letras De Talca": "TALCA",
    "2° Juzgado De Letras De Linares": "LINARES",
    "1° Juzgado De Letras De Linares": "LINARES",
    "1° Juzgado De Letras De Talca": "TALCA",
    "2° Juzgado De Letras De Curico": "CURICO",
    "Juzgado De Letras De Constitucion": "CONSTITUCION",
    "Juzgado De Letras De San Javier": "SAN JAVIER",
    "Unidad Apoyo Técnico Administrativo De Talca": "TALCA",
    // --- SANTIAGO Y ALREDEDORES ---
    "10° Juzgado Civil De Santiago": "SANTIAGO",
    "11° Juzgado Civil De Santiago": "SANTIAGO",
    "18° Juzgado Civil De Santiago": "SANTIAGO",
    "22° Juzgado Civil De Santiago": "SANTIAGO",
    "23° Juzgado Civil De Santiago": "SANTIAGO",
    "6° Juzgado Civil De Santiago": "SANTIAGO",
    "9° Juzgado Civil De Santiago": "SANTIAGO",
    "2° Juzgado De Familia De Santiago": "SANTIAGO",
    "Juzgado De Familia De Pudahuel": "PUDAHUEL",
    "1° Juzgado De Letras De San Bernardo": "SAN BERNARDO",
    "Juzgado De Familia De Melipilla": "MELIPILLA",
    "4° Juzgado De Familia De Santiago": "SANTIAGO",
    "15° Juzgado Civil De Santiago": "SANTIAGO",
    "16° Juzgado Civil De Santiago": "SANTIAGO",
    "2° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "20° Juzgado Civil De Santiago": "SANTIAGO",
    "21° Juzgado Civil De Santiago": "SANTIAGO",
    "24° Juzgado Civil De Santiago": "SANTIAGO",
    "3° Juzgado De Familia De Santiago": "SANTIAGO",
    "7° Juzgado Civil De Santiago": "SANTIAGO",
    "Juzgado De Garantia De Colina": "COLINA",
    "1° Juzgado De Familia De Santiago": "SANTIAGO",
    "10° Juzgado De Garantia De Santiago": "SANTIAGO",
    "1° Juzgado De Familia De San Miguel": "SANTIAGO",
    "12° Juzgado Civil De Santiago": "SANTIAGO",
    "13° Juzgado Civil De Santiago": "SANTIAGO",
    "14° Juzgado Civil De Santiago": "SANTIAGO",
    "17° Juzgado Civil De Santiago": "SANTIAGO",
    "19° Juzgado Civil De Santiago": "SANTIAGO",
    "1° Juzgado Civil De Santiago": "SANTIAGO",
    "2° Juzgado De Familia De San Miguel": "SANTIAGO",
    "1° Juzgado Civil De Puente Alto": "PUENTE ALTO",
    "15° Juzgado De Garantia De Santiago": "SANTIAGO",
    "1° Juzgado Civil De San Miguel": "SAN MIGUEL",
    "11° Juzgado De Garantia De Santiago": "SANTIAGO",
    "12° Juzgado De Garantia De Santiago": "SANTIAGO",
    "Corte Suprema De Justicia": "SANTIAGO",
    "Juzgado De Familia De Puente Alto": "PUENTE ALTO",
    "Juzgado De Familia De Buin": "BUIN",
    "Juzgado De Familia De San Bernardo": "SAN BERNARDO",
    "Juzgado De Garantia De Curacavi": "CURACAVI",
    "Juzgado De Garantia De Melipilla": "MELIPILLA",
    "Juzgado De Garantia De Puente Alto": "SANTIAGO",
    "Juzgado De Garantia De San Bernardo": "SANTIAGO",
    "Juzgado De Garantia De Talagante": "TALAGANTE",
    "Tribunal De Juicio Oral En Lo Penal De Puente Alto": "SANTIAGO",
    "Juzgado De Familia De PeÑaflor": "PEÑAFLOR",
    "Tribunal De Juicio Oral En Lo Penal De San Bernardo": "SANTIAGO",
    "Juzgado De Familia De Talagante": "TALAGANTE",
    "Corte De Apelaciones De Santiago": "SANTIAGO",
    "7° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "8° Juzgado De Garantia De Santiago": "SANTIAGO",
    "Juzgado De Familia De Colina": "COLINA",
    "Tribunal De Juicio Oral En Lo Penal De Talagante": "TALAGANTE",
    "1° Juzgado De Letras Del Trabajo De Santiago": "SANTIAGO",
    "2° Juzgado De Garantia De Santiago": "SANTIAGO",
    "30° Juzgado Civil De Santiago": "SANTIAGO",
    "6° Juzgado De Garantia De Santiago": "SANTIAGO",
    "6° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "14°Juzgado De Garantia De Santiago": "SANTIAGO",
    "1° Juzgado De Letras De Buin": "BUIN",
    "2° Juzgado De Letras De San Bernardo": "SAN BERNARDO",
    "8° Juzgado Civil De Santiago": "SANTIAGO",
    "2° Juzgado De Letras Del Trabajo De Santiago": "SANTIAGO",
    "26° Juzgado Civil De Santiago": "SANTIAGO",
    "Juzgado De Letras Del Trabajo De Puente Alto": "PUENTE ALTO",
    "Juzgado De Letras Del Trabajo De San Bernardo": "SAN BERNARDO",
    "Juzgado De Letras Del Trabajo De San Miguel": "SAN MIGUEL",
    "Tribunal De Juicio Oral En Lo Penal De Melipilla": "MELIPILLA",
    "Juzgado De Letras De Colina": "COLINA",
    "Juzgado De Letras De PeÑaflor": "PEÑAFLOR",
    "Corporacion Administrativa De San Miguel": "SAN MIGUEL",
    "1° Juzgado De Garantia De Santiago": "SANTIAGO",
    "34° Juzgado Del Crimen De Santiago": "SANTIAGO",
    "7° Juzgado De Garantia De Santiago": "SANTIAGO",
    "1° Juzgado De Letras De Melipilla": "MELIPILLA",
    "25° Juzgado Civil De Santiago": "SANTIAGO",
    "27° Juzgado Civil De Santiago": "SANTIAGO",
    "28° Juzgado Civil De Santiago": "SANTIAGO",
    "29° Juzgado Civil De Santiago": "SANTIAGO",
    "1° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "2° Juzgado Civil De Santiago": "SANTIAGO",
    "Corporacion Administrativa Central - Departamento De PlanificaciÓn": "SANTIAGO",
    "Corporacion Administrativa De Santiago": "SANTIAGO",
    "1° Juzgado De Letras De Talagante": "TALAGANTE",
    "13° Juzgado De Garantia De Santiago": "SANTIAGO",
    "5° Juzgado Civil De Santiago": "SANTIAGO",
    "3° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "4° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "5° Tribunal De Juicio Oral En Lo Penal De Santiago": "SANTIAGO",
    "4° Juzgado Civil De Santiago": "SANTIAGO",
    "3° Juzgado Civil De Santiago": "SANTIAGO",
    "4° Juzgado Civil De San Miguel": "SAN MIGUEL",
    "Juzgado De Cobranza Laboral Y Previsional De San Miguel": "SAN MIGUEL",
    "2° Juzgado De Letras De Talagante": "TALAGANTE",
    "Corte De Apelaciones De San Miguel": "SAN MIGUEL",
    "9° Juzgado De Garantia De Santiago": "SANTIAGO",
    "4° Juzgado De Garantia De Santiago": "SANTIAGO",
    "Tribunal De Juicio Oral En Lo Penal De Colina": "COLINA",
    "Juzgado De Cobranza Laboral Y Previsional De Santiago": "SANTIAGO",
    "3° Juzgado De Garantia De Santiago": "SANTIAGO",
    "5° Juzgado De Garantia De Santiago": "SANTIAGO",
    "Centro De Justicia De Santiago": "SANTIAGO",
    "2° Juzgado Civil De San Miguel": "SAN MIGUEL",
    "Corporacion Administrativa Central - Justicia Movil": "SANTIAGO",
    "Centro De Justicia De Santiago - Administracion Cjs": "SANTIAGO",
    "Corporacion Administrativa Central - Finanzas": "SANTIAGO",
    "Corporacion Administrativa Central - Unidad JurÍdica": "SANTIAGO",
    "Corporacion Administrativa Central - Informática": "SANTIAGO",
    "Corte Suprema De Justicia - Biblioteca Cs": "SANTIAGO",
    "Corte Suprema De Justicia - Oficina De Extradicion Cs": "SANTIAGO",
    "2° Juzgado De Letras De Buin": "BUIN",
    "3° Juzgado Civil De San Miguel": "SAN MIGUEL",
    "Corporacion Administrativa Central - Adquisiciones Y Mantenimiento": "SANTIAGO",
    "Corporacion Administrativa Central - Centro Documental": "SANTIAGO",
    "Corporacion Administrativa Central - Recursos Humanos": "SANTIAGO",
    "Corte Suprema De Justicia - Ministros Cs": "SANTIAGO",
    "Corporacion Administrativa Central - Centro De Notificaciones": "SANTIAGO",
    "Corte Suprema De Justicia - Relatores Cs": "SANTIAGO",
    "Corporacion Administrativa Central - Bienestar": "SANTIAGO",
    "Corte Suprema De Justicia - Fiscalia Cs": "SANTIAGO",
    "Apoyo Juzgados Civiles": "SANTIAGO",
    "Centro Apoyo Juzgados Civiles Y Laborales Santiago": "SANTIAGO",
    "Centro De Notificaciones Judiciales C.J. Santiago": "SANTIAGO",
    "Centro Medidas Cautelares Jdos. Familia Santiago": "SANTIAGO",
    "Administracion Externa Centro De Justicia De Stgo.": "SANTIAGO",
    "Unidad De Protecciones I.c.a. De Santiago": "SANTIAGO",
    "Centro Atencion Asuntos De Familia De Santiago": "SANTIAGO",
    "Unidad Admtva. Tramit. Lab. Y Cobr. Prev. Santiago": "SANTIAGO",
    "Centro de notificaciones de colina": "COLINA",
    // --- CHILLAN ---
    "1° Juzgado De Letras De San Carlos": "SAN CARLOS",
    "Juzgado De Letras Del Trabajo De Chillan": "CHILLAN",
    "1° Juzgado Civil De Chillan": "CHILLAN",
    "Juzgado De Familia De Chillan": "CHILLAN",
    "Corporacion Administrativa De Chillan": "CHILLAN",
    "Juzgado De Garantia De Chillan": "CHILLAN",
    "Juzgado De Letras Y Garantia De Quirihue": "QUIRIHUE",
    "Juzgado De Letras De Yungay": "YUNGAY",
    "Juzgado De Garantia De San Carlos": "SAN CARLOS",
    "Tribunal De Juicio Oral En Lo Penal De Chillan": "CHILLAN",
    "2° Juzgado Civil De Chillan": "CHILLAN",
    "Juzgado De Letras Y Garantia De Bulnes": "BULNES",
    "Juzgado De Letras Y Garantia De Coelemu": "COELEMU",
    "Corte De Apelaciones De Chillan": "CHILLAN",
    "Juzgado De Garantia De Yungay": "YUNGAY",
    "Oficina De Personal De Chillan": "CHILLAN",
    // --- IQUIQUE ---
    "Juzgado De Letras Del Trabajo De Iquique": "IQUIQUE",
    "1° Juzgado De Letras De Iquique": "IQUIQUE",
    "Juzgado De Letras Del Trabajo De Iquique Departamento": "IQUIQUE",
    "3° Juzgado De Letras De Iquique": "IQUIQUE",
    "Juzgado De Garantia De Iquique": "IQUIQUE",
    "Corte De Apelaciones De Iquique": "IQUIQUE",
    "Juzgado De Letras Y Garantia De Pozo Almonte": "POZO ALMONTE",
    "2° Juzgado De Letras De Iquique": "IQUIQUE",
    "Corporacion Administrativa De Iquique": "IQUIQUE",
    "Tribunal de Juicio Oral En Lo Penal De Iquique": "IQUIQUE",
    "Centro De Notificaciones Judiciales De Iquique": "IQUIQUE",
    "Juzgado De Familia De Iquique": "IQUIQUE",
    "Juzgado De Letras De Familia Garantia Y Trabajo De Alto Hospicio": "ALTO HOSPICIO",
    "Centro De Observ. Y Control De Cump. De Medidas De Protec. De Familia Iquique": "IQUIQUE",
    "Juzgado De Letras De Familia-garantia Y Trabajo De Alto Hospicio": "ALTO HOSPICIO",
    // --- VALPARAISO Y VIÑA ---
    "Corte De Apelaciones De Valparaiso": "VALPARAISO",
    "Juzgado De Familia De La Ligua": "LA LIGUA",
    "Juzgado De Familia De Los Andes": "LOS ANDES",
    "Juzgado De Familia De Quillota": "QUILLOTA",
    "Juzgado De Letras Del Trabajo De San Felipe": "SAN FELIPE",
    "Juzgado de Familia de Casablanca": "CASABLANCA",
    "1° Juzgado Civil De Valparaiso": "VALPARAISO",
    "1° Juzgado De Letras De Los Andes": "LOS ANDES",
    "1° Juzgado De Letras De Quillota": "QUILLOTA",
    "1° Juzgado De Letras De Quilpue": "QUILPUE",
    "1° Juzgado De Letras De San Antonio": "SAN ANTONIO",
    "1° Juzgado De Letras De San Felipe": "SAN FELIPE",
    "1° Juzgado Civil De ViÑa Del Mar": "VIÑA DEL MAR",
    "3° Juzgado Civil De Viña Del Mar": "VIÑA DEL MAR",
    "2° Juzgado De Letras De Quillota": "QUILLOTA",
    "2° Juzgado De Letras De San Antonio": "SAN ANTONIO",
    "Juzgado De Familia De Quilpue": "QUILPUE",
    "Juzgado De Familia De San Antonio": "SAN ANTONIO",
    "Juzgado De Familia De San Felipe": "SAN FELIPE",
    "Juzgado De Familia De Valparaiso": "VALPARAISO",
    "Juzgado De Familia De Villa Alemana": "VILLA ALEMANA",
    "Juzgado De Garantia De La Ligua": "LA LIGUA",
    "Juzgado De Letras De Calera": "CALERA",
    "Juzgado De Garantia De Quilpue": "QUILPUE",
    "Juzgado De Garantia De Limache": "LIMACHE",
    "Juzgado De Garantia De San Antonio": "SAN ANTONIO",
    "Juzgado De Garantia De Los Andes": "LOS ANDES",
    "Tribunal Juicio Oral En Lo Penal De Viña Del Mar": "VIÑA DEL MAR",
    "2° Juzgado Civil De Valparaiso": "VALPARAISO",
    "3° Juzgado Civil De Valparaiso": "VALPARAISO",
    "5° Juzgado Civil De Valparaiso": "VALPARAISO",
    "Juzgado De Cobranza Laboral Y Previsional De Valparaiso": "VALPARAISO",
    "Juzgado De Letras Del Trabajo De Valparaiso": "VALPARAISO",
    "Tribunal De Juicio Oral En Lo Penal De Valparaiso": "VALPARAISO",
    "Corporacion Administrativa De Valparaiso": "VALPARAISO",
    "Juzgado de Letras Y Garantia De Quintero": "QUINTERO",
    "Juzgado De Garantia De Viña Del Mar": "VIÑA DEL MAR",
    "Juzgado De Garantia De Valparaiso": "VALPARAISO",
    "Juzgado De Familia De Limache": "LIMACHE",
    "2° Juzgado Civil De ViÑa Del Mar": "VIÑA DEL MAR",
    "2° Juzgado De Letras De Los Andes": "LOS ANDES",
    "2° Juzgado De Letras De Quilpue": "QUILPUE",
    "Juzgado De Familia De ViÑa Del Mar": "VIÑA DEL MAR",
    "Juzgado De Garantia De Calera": "CALERA",
    "Juzgado De Garantia De Quillota": "QUILLOTA",
    "Juzgado De Garantia De San Felipe": "SAN FELIPE",
    "Juzgado De Garantia De Villa Alemana": "VILLA ALEMANA",
    "Juzgado De Letras De Casablanca": "CASABLANCA",
    "Juzgado De Letras De La Ligua": "LA LIGUA",
    "Juzgado De Letras De Limache": "LIMACHE",
    "Juzgado De Letras De Villa Alemana": "VILLA ALEMANA",
    "Juzgado De Letras Y Garantia De Petorca": "PETORCA",
    "Juzgado De Letras Y Garantia De Putaendo": "PUTAENDO",
    "Tribunal De Juicio Oral En Lo Penal De Quillota": "QUILLOTA",
    "Tribunal De Juicio Oral En Lo Penal De San Antonio": "SAN ANTONIO",
    "Tribunal De Juicio Oral En Lo Penal De San Felipe": "SAN FELIPE",
    "4° Juzgado Civil De Valparaiso": "VALPARAISO",
    "Juzgado De Letras Y Garantia De Isla De Pascua": "VALPARAISO",
    "Juzgado De Garantia De Casablanca": "CASABLANCA",
    "Tribunal De Juicio Oral En Lo Penal De Los Andes": "LOS ANDES",
    "Centro De Notificaciones Judiciales De Valparaiso": "VALPARAISO"
};